add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
set_languages("cxx2b")
set_warnings("all")
add_cxflags("-fno-permissive", {force = true})
add_cxflags("-std=c++20 -pedantic", {force = true})
add_cxflags("-Wconversion", {force = true})

add_requires("asio")
add_requires("benchmark")
add_requires("catch2")
add_requires("fmt")
add_requires("gflags")
add_requires("gtest")
add_requires("magic_enum")
add_requires("protoc", "protobuf-cpp")
add_requires("spdlog")

add_includedirs("third_party/leaf/")
add_includedirs("third_party/proxy/")
add_includedirs("include/")
add_includedirs("include/quorum")
add_includedirs("include/tracker")

target("lepton-raft")
    set_kind("binary")
    add_rules("protobuf.cpp")
    add_packages("asio", "fmt", "magic_enum", "protoc", "protobuf-cpp", "spdlog")
    add_files("src/tracker/*.cpp")
    add_files("src/*.cpp")
    add_files("proto/**.proto", {proto_rootdir = "proto"})

target("lepton-unit-test")
    add_defines("LEPTON_TEST")
    add_defines("LEPTON_PROJECT_DIR=\"$(curdir)\"")
    add_includedirs("test/utility/include")
    add_files("test/unit_test.cpp")
    add_files("test/asio/*.cpp")
    add_files("test/quorum/*.cpp")
    add_files("test/tracker/*.cpp")
    add_files("test/utility/src/*.cpp")
    add_packages("asio", "fmt", "magic_enum", "protoc", "protobuf-cpp", "spdlog")
    add_packages("catch2")
    add_packages("gtest", "benchmark")


target("lepton-benchmark-test")
    add_defines("LEPTON_TEST")
    add_files("test/benchmark.cpp")
    add_files("test/quorum/benchmark_test.cpp")
    add_packages("asio", "fmt", "magic_enum", "protoc", "protobuf-cpp", "spdlog")
    add_packages("gtest", "benchmark")    
